
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 08 18:20:02 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 27;
  public static final int JEDNAKOJEDNAKO = 38;
  public static final int DVOTACKA = 44;
  public static final int PROCENAT = 28;
  public static final int LOGICKOI = 21;
  public static final int CONST = 31;
  public static final int ZVEZDICA = 33;
  public static final int CASE = 40;
  public static final int CONTINUE = 50;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int VECEJEDNAKO = 32;
  public static final int MINUS = 25;
  public static final int RAZLICITO = 37;
  public static final int RPAREN = 7;
  public static final int PODELJENO = 30;
  public static final int DUGLASTA = 46;
  public static final int MANJEJEDNAKO = 36;
  public static final int COMMA = 11;
  public static final int CLASS = 49;
  public static final int PLUS = 10;
  public static final int IF = 18;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 26;
  public static final int RETURN = 9;
  public static final int EQUAL = 8;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int NUMBER = 14;
  public static final int BREAK = 39;
  public static final int IDENT = 15;
  public static final int VOID = 13;
  public static final int LOGICKOILI = 29;
  public static final int SWITCH = 24;
  public static final int PITANJE = 43;
  public static final int MANJE = 20;
  public static final int LBRACE = 3;
  public static final int ELSE = 19;
  public static final int VECE = 41;
  public static final int READ = 42;
  public static final int ENUM = 35;
  public static final int WHILE = 45;
  public static final int CHARCONST = 16;
  public static final int TACKA = 34;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 17;
  public static final int EXTENDS = 22;
  public static final int PROG = 2;
  public static final int LUGLASTA = 47;
  public static final int DO = 48;
  public static final int PRINT = 12;
}

